const { chromium } = require('../tmp/browser-check/node_modules/playwright');
const assert = require('node:assert/strict');

(async () => {
  const browser = await chromium.launch({ channel: 'msedge', headless: true });
  const context = await browser.newContext({ viewport: { width: 390, height: 844 }, serviceWorkers: 'block' });
  const page = await context.newPage();
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  const base = process.env.BANJANG_TEST_URL || 'http://127.0.0.1:8018';
  const shot = name => page.screenshot({ path: `tmp/browser-check/${name}.png`, fullPage: true });
  await page.goto(base);
  await page.getByRole('button', {name: '관리자 · 반장 출근하기'}).click();
  await page.getByPlaceholder('예: 2층에서 용접 작업, 주변에 합판이 있습니다.').fill('2층 각파이프 용접, 옆에 합판');
  await page.getByRole('button', {name: '새 체크리스트 만들기'}).click();
  await page.getByRole('dialog').getByLabel('작업자 이름').selectOption('2');
  await page.getByLabel('주변 가연물', {exact: true}).fill('없음');
  await page.getByPlaceholder('예: 현장 확인 위치·방법·확인자').fill('반장이 현장 작업 반경을 직접 확인하여 가연물 없음을 확인했습니다.');
  await page.getByRole('button', {name: '검토기록 저장 후 체크리스트 보기'}).click();
  await page.getByRole('button', {name: 'TBM 기록하기'}).click();
  let tbmRequests = 0;
  let failTbm = true;
  await page.route('**/api/tbm', async route => {
    if (route.request().method() !== 'POST') return route.continue();
    tbmRequests++;
    await new Promise(resolve => setTimeout(resolve, 300));
    if (failTbm) { failTbm = false; return route.fulfill({status: 503, json: {detail: '검증용 일시 오류'}}); }
    return route.continue();
  });
  await page.getByPlaceholder('오늘 다룬 안전 수칙을 입력하세요.').fill('소화기 위치와 환기를 확인합니다.');
  await page.getByRole('button', {name: 'TBM 저장·누락 확인'}).click();
  await page.getByText('검증용 일시 오류', {exact:true}).waitFor();
  assert.equal(await page.getByPlaceholder('오늘 다룬 안전 수칙을 입력하세요.').inputValue(), '소화기 위치와 환기를 확인합니다.');
  await page.locator('form').evaluate(form => { form.requestSubmit(); form.requestSubmit(); });
  await page.getByText('TBM 기록을 저장했습니다.', {exact:true}).waitFor();
  assert.equal(tbmRequests, 2, 'one failed attempt and one successful attempt, no double submit');
  assert(await page.getByRole('button', {name: 'TBM 저장 완료'}).isDisabled());
  await shot('tbm-saved');
  await page.getByRole('button', {name: '사진 증빙으로 이동'}).click();
  await page.getByText('모의 판정 모드 · 실제 사진을 분석하지 않습니다.', {exact:true}).waitFor();
  await page.getByText('개발용 mock 실패 재현', {exact:true}).click();
  await page.getByLabel('시연용 mock 결과 사용').check();
  const png = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=', 'base64');
  await page.getByLabel('증빙 사진').setInputFiles({name:'test.png',mimeType:'image/png',buffer:png});
  await page.getByRole('button', {name:'모의 사진 판정 요청'}).click();
  await page.getByText(/모의 판정 \(실제 사진 분석 아님\)/).waitFor();
  await shot('mock-evidence');
  await page.getByPlaceholder('조치 사유').first().fill('모의 판정 검증: 반장이 조치 항목을 직접 확인했습니다.');
  await page.getByRole('button', {name:'직접 확인'}).first().click();
  await page.getByText('관리자 조치를 저장했습니다.', {exact:true}).waitFor();
  await page.getByRole('link', {name:'기록',exact:true}).click();
  const adminScores = await (await context.request.get(base+'/api/scores')).json();
  assert.equal(adminScores.total,10);
  await page.getByRole('button', {name:'퇴근하기'}).click();
  await page.getByRole('radio', {name:/근로자/}).click();
  await page.getByRole('button', {name:'근로자 출근하기'}).click();
  await page.getByLabel('오늘 작업 내용', {exact:true}).fill('용접 작업을 마쳤습니다.');
  await page.getByLabel('위험하거나 확인이 필요한 점', {exact:true}).fill('통로를 정리해 주세요.');
  await page.getByLabel('사진 첨부 (선택)', {exact:true}).setInputFiles({name:'close.png',mimeType:'image/png',buffer:png});
  let forms = 0, uploads = 0;
  await page.route('**/api/worker-forms', async route => {
    if (route.request().method() === 'POST') { forms++; await new Promise(resolve => setTimeout(resolve, 300)); }
    return route.continue();
  });
  await page.route('**/api/worker-forms/*/photo', async route => {
    uploads++;
    if (uploads === 1) return route.fulfill({status:503,json:{detail:'검증용 사진 업로드 실패'}});
    return route.continue();
  });
  await page.locator('form').evaluate(form => { form.requestSubmit(); form.requestSubmit(); });
  await page.getByText(/보고 내용은 저장됐지만 사진 첨부에 실패했습니다/).waitFor();
  await page.getByRole('button', {name:'사진 첨부 다시 시도'}).click();
  await page.getByText('마감 보고를 제출했습니다. 관리자 검토함에서 확인할 수 있습니다.', {exact:true}).waitFor();
  assert.equal(forms,1); assert.equal(uploads,2);
  assert(await page.getByRole('button', {name:'마감 보고 제출 완료'}).isDisabled());
  const saved = await (await context.request.get(base+'/api/worker-forms')).json();
  assert.equal(saved.length,1); assert.equal(saved[0].ppe_worn,null); assert.equal(saved[0].understood,null);
  await shot('worker-submitted');
  await page.getByRole('link', {name:'내 기록',exact:true}).click();
  const workerScores = await (await context.request.get(base+'/api/scores?worker_id=2')).json();
  assert.equal(workerScores.total,3);
  await page.getByRole('button', {name:'퇴근하기'}).click();
  await page.getByRole('button', {name:'관리자 · 반장 출근하기'}).click();
  await page.getByRole('link', {name:'작업자관리',exact:true}).waitFor();
  await page.goto(base + '/#/reviews');
  await page.getByText('보호구 착용: 미확인 · 수칙 이해: 미확인', {exact:true}).waitFor();
  await page.getByText('보호구 착용: 미확인 · 수칙 이해: 미확인', {exact:true}).scrollIntoViewIfNeeded();
  await shot('manager-unknown');
  assert.deepEqual(errors,[]);
  console.log(JSON.stringify({passed:true,tbmRequests,forms,uploads,adminTotal:adminScores.total,workerTotal:workerScores.total,pageErrors:errors},null,2));
  await browser.close();
})().catch(error => { console.error(error); process.exit(1); });
