const { chromium } = require('../tmp/browser-check/node_modules/playwright');
const assert = require('node:assert/strict');
(async () => {
  const browser = await chromium.launch({ channel: 'msedge', headless: true });
  const context = await browser.newContext({ viewport: { width: 390, height: 844 }, serviceWorkers: 'block' });
  const page = await context.newPage();
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  const base = process.env.BANJANG_TEST_URL || 'http://127.0.0.1:8026';
  await page.goto(base);
  await page.getByRole('button', { name: '관리자 · 반장 출근하기' }).click();
  await page.getByRole('navigation').waitFor();
  assert.deepEqual(await page.getByRole('navigation').getByRole('link').allTextContents(), ['TBM', '작업자관리', '캘린더', 'JSA', '기록']);
  await page.getByRole('checkbox', { name: '근로자 마감 보고 요청' }).uncheck();
  assert(await page.getByRole('button', { name: '새 체크리스트 만들기' }).isEnabled());
  await page.getByPlaceholder('예: 2층에서 용접 작업, 주변에 합판이 있습니다.').fill('2층 용접 작업, 주변에 합판');
  await page.getByRole('button', { name: '새 체크리스트 만들기' }).click();
  const dialog = page.getByRole('dialog');
  await dialog.getByLabel('작업자 이름').selectOption('2');
  await dialog.getByLabel('작업 층', { exact: true }).fill('3층');
  await dialog.getByRole('button', { name: '임시저장', exact: true }).click();
  await dialog.getByRole('button', { name: '닫기', exact: true }).click();
  await page.getByRole('button', { name: '관리자 검토 이어가기' }).click();
  assert.equal(await dialog.getByLabel('작업 층', { exact: true }).inputValue(), '3층');
  assert.equal(await dialog.getByLabel('작업자 이름').inputValue(), '2');
  await page.screenshot({ path: 'tmp/browser-check/admin-review.png' });
  await dialog.getByRole('button', { name: '검토기록 저장 후 체크리스트 보기' }).click();
  await page.getByRole('heading', { name: '안전 체크리스트' }).waitFor();
  await page.getByRole('link', { name: '작업자관리' }).click();
  await page.getByText('김OO', { exact: true }).first().waitFor();
  await page.screenshot({ path: 'tmp/browser-check/admin-workers.png' });
  for (let i = 0; i < 3; i++) await context.request.post(base + '/api/tasks', { data: { text: `용접 작업 ${i + 1}`, worker_id: 2 } });
  await page.getByRole('link', { name: '캘린더' }).click();
  await page.getByRole('button', { name: /작업 .*더보기/ }).first().click();
  assert(await page.getByRole('dialog').getByText('용접 작업 3', { exact: true }).first().isVisible());
  await page.getByRole('dialog').getByRole('button', { name: '닫기' }).click();
  await page.screenshot({ path: 'tmp/browser-check/admin-calendar.png' });
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth));
  await page.getByRole('link', { name: '기록', exact: true }).click();
  await page.getByText('아직 점수를 받은 작업자가 없습니다.').waitFor();
  await page.getByRole('button', { name: '퇴근하기' }).click();
  await page.getByRole('radio', { name: /근로자/ }).click();
  await page.getByRole('button', { name: '근로자 출근하기' }).click();
  await page.getByRole('navigation').waitFor();
  assert.deepEqual(await page.getByRole('navigation').getByRole('link').allTextContents(), ['오늘작업', '사진', '캘린더', '내 기록']);
  assert.deepEqual(errors, []);
  await browser.close();
  console.log('PASS: mobile tabs, unchecked closeout, shared modal, draft restoration, assignment, calendar more, records; no browser errors');
})().catch(error => { console.error(error); process.exit(1); });
