import { useEffect, useState } from 'react';
import { Camera, Check, RefreshCw, Search } from 'lucide-react';
import { api, post } from '../lib/api.js';
import { AppButton, EmptyState, Panel, Screen } from '../components/ui.jsx';

export default function Evidence() {
  const [task, setTask] = useState(null); const [items, setItems] = useState([]); const [files, setFiles] = useState({}); const [scenario, setScenario] = useState('verify_reject'); const [message, setMessage] = useState(''); const [queue, setQueue] = useState([]); const [reasons, setReasons] = useState({});
  const taskId = localStorage.getItem('banjang.taskId');
  async function load() { const [t, q] = await Promise.all([api('/tasks/' + taskId), api('/evidence/review-queue')]); setTask(t); setItems(t.checklist); setQueue(q); }
  useEffect(() => { if (taskId) load().catch(e => setMessage(e.message)); }, []);
  async function submit(item) { const body = new FormData(); body.append('task_id', taskId); body.append('item_code', item.code); body.append('photo', files[item.code] || new Blob(['demo photo'], { type: 'image/jpeg' }), 'demo.jpg'); body.append('forced_result', 'confirmed'); body.append('scenario', scenario); try { const r = await api('/evidence', { method: 'POST', body }); setMessage(`판정 ${r.result}, 확인 점수 ${r.points}점`); await load(); } catch (e) { setMessage(e.message); } }
  async function review(id, action) { try { await post(`/evidence/${id}/reviews`, { action, reason: reasons[id] || '사진과 체크리스트 항목을 대조해 확인했습니다.' }); setMessage('관리자 조치를 저장했습니다.'); await load(); } catch(e) { setMessage(e.message); } }
  return <Screen title="사진 검토"><Panel><p className="text-sm text-ink-sub">모델 판정 실패와 검증 불일치는 검토 대기로 보냅니다. 이 상태에서는 점수를 주지 않습니다.</p><label className="mt-3 block text-sm">Mock 실패 시나리오<select value={scenario} onChange={e => setScenario(e.target.value)} className="mt-2 w-full rounded-xl border border-line p-3"><option value="verify_reject">검증 불일치</option><option value="judge_fail">판정 응답 오류</option><option value="judge_timeout">timeout</option><option value="judge_invalid">잘못된 응답</option><option value="verify_empty">빈 검증 근거</option></select></label><input aria-label="시연 사진" type="file" accept="image/*" onChange={e => setFiles({ ...files, [items[0]?.code]: e.target.files?.[0] })} className="mt-3 w-full text-sm" /></Panel>{items.map(item => <Panel key={item.code} className="mt-4"><b>{item.title}</b><AppButton className="mt-3 w-full" onClick={() => submit(item)}><Camera className="mr-2 inline" size={18} />실패 사진 판정 재현</AppButton></Panel>)}<h2 className="mx-[22px] mt-6 text-lg font-bold">관리자 검토 대기</h2>{queue.length === 0 && <EmptyState icon={Search} title="대기 사진 없음" />}{queue.map(row => <Panel key={row.id} className="mt-3"><img src={row.photo_url} alt="검토 대상 사진" className="w-full rounded-xl"/><h3 className="mt-3 font-bold">{row.title} · {row.result}</h3><p className="mt-1 text-sm text-danger">{row.observed}</p><p className="text-sm text-ink-sub">{row.retake_hint}</p><input className="mt-3 w-full rounded-xl border border-line p-3" placeholder="조치 사유" value={reasons[row.id] || ''} onChange={e => setReasons({ ...reasons, [row.id]: e.target.value })}/><div className="mt-3 grid grid-cols-2 gap-2"><AppButton onClick={() => review(row.id, 'retake_requested')}><RefreshCw className="mr-1 inline" size={16}/>재촬영 요청</AppButton><AppButton onClick={() => review(row.id, 'confirmed_by_manager')}><Check className="mr-1 inline" size={16}/>직접 확인</AppButton></div>{row.reviews.map(review => <p key={review.id} className="mt-2 text-sm">{review.action}: {review.reason}</p>)}</Panel>)}{message && <p role="status" className="mx-[22px] mt-4 text-sm">{message}</p>}</Screen>;
}
