import { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { readSession } from '../lib/session.js';
import { api, post } from '../lib/api.js';
import { AppButton, Panel, Screen } from '../components/ui.jsx';
export default function WorkerForm() {
 const { taskId: routeTaskId }=useParams(); const taskId = routeTaskId || (() => { try { return localStorage.getItem('banjang.taskId') || 'missing'; } catch { return 'missing'; } })(); const [reportText,setReportText]=useState(''); const [riskNote,setRiskNote]=useState(''); const [photo,setPhoto]=useState(null); const [message,setMessage]=useState(''); const [task,setTask]=useState(null); const [tbm,setTbm]=useState(null); const [loadError,setLoadError]=useState('');
 useEffect(()=>{if(taskId === 'missing') return; Promise.all([api('/tasks/'+taskId),api('/tbm/latest?task_id='+taskId).catch(error=>error.status === 404 ? null : Promise.reject(error))]).then(([savedTask,latestTbm])=>{setTask(savedTask);setTbm(latestTbm);}).catch(error=>setLoadError(error.message));},[taskId]);
 if (taskId === 'missing') return <Screen title="오늘 작업"><Panel><p className="font-bold">관리자가 먼저 오늘 작업을 등록해야 합니다</p><p className="mt-2 text-sm text-ink-sub">관리자가 작업을 등록한 뒤 다시 출근해 주세요.</p></Panel></Screen>;
 async function submit(e){e.preventDefault(); try { const form=await post('/worker-forms',{task_id:Number(taskId),report_text:reportText,risk_note:riskNote,ppe_worn:null,understood:null,worker_id:readSession()?.worker_id || 2}); if(photo){const body=new FormData();body.append('photo',photo);await api('/worker-forms/'+form.id+'/photo',{method:'POST',body});} setMessage('마감 보고를 제출했습니다. 관리자 검토함에서 확인할 수 있습니다.'); } catch(err){setMessage(err.message)}}
 return <Screen title="오늘 작업"><div className="space-y-4"><Panel><b>오늘 작업</b><p className="mt-2 text-ink-sub">{task?.text || '작업 내용을 불러오는 중입니다.'}</p></Panel><Panel><b>관리자 TBM 내용</b>{tbm ? <><p className="mt-2 whitespace-pre-wrap text-ink">{tbm.transcript}</p>{tbm.memo&&<p className="mt-3 text-sm text-ink-sub">메모: {tbm.memo}</p>}</> : <p className="mt-2 text-sm text-warn">저장된 TBM이 없습니다. 관리자에게 확인해 주세요.</p>}</Panel><Panel><b>오늘 확인할 필수 안전 수칙</b>{task?.checklist?.filter(item=>item.level === 'required').map(item=><p key={item.code} className="mt-2 text-sm">• {item.title}</p>)}{tbm?.missing?.length > 0&&<div className="mt-3 rounded-xl bg-warn-soft p-3 text-sm"><b>TBM에서 누락된 필수 수칙</b>{tbm.missing.map(item=><p key={item.code} className="mt-1">• {item.title}</p>)}</div>}</Panel>{loadError&&<p role="alert" className="mx-[22px] text-danger">{loadError}</p>}<form onSubmit={submit}><Panel><b>마감 보고</b><label className="mt-4 block">오늘 작업 내용<textarea value={reportText} onChange={e=>setReportText(e.target.value)} className="mt-2 min-h-24 w-full rounded-2xl border border-line p-3" /></label><label className="mt-4 block">위험하거나 확인이 필요한 점<textarea value={riskNote} onChange={e=>setRiskNote(e.target.value)} className="mt-2 min-h-24 w-full rounded-2xl border border-line p-3" /></label><label className="mt-4 block">사진 첨부 (선택)<input type="file" accept="image/*" onChange={e=>setPhoto(e.target.files?.[0])} className="mt-2 block w-full" /></label></Panel><div className="mx-[22px] mt-5"><AppButton big className="w-full">마감 보고 제출</AppButton></div>{message&&<p className="mx-[22px] mt-3 text-center text-ink-sub">{message}</p>}</form></div></Screen>;
}
